logging:
  level.: DEBUG
  config: classpath:log4j2.properties

server:
  port: 8865

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: sql2016.
  jpa:
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    show-sql: true